[project]
name = "book-spine-model-to-onnx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "onnx>=1.17.0",
    "onnxruntime>=1.21.1",
    "onnxslim>=0.1.51",
    "ultralytics>=8.3.127",
]
